#!/bin/bash


# Get the absolute path to the .gitignore file
gitignore_file=.gitignore

# read every line in the .gitignore file
while IFS= read -r line; do
    # folder in .gitignore is *folderName* should become folderName
    folderName=$(echo "$line" | sed 's/*//g')

    echo "Deleting $folderName"
    rm -rf $folderName
done < .gitignore

# clean the .gitignore file
echo "# This file is autogenerated" > .gitignore

echo "Cleaning completed."